### PR TITLE
TP Progress Support

### PR DESCRIPTION
**Pull request by Trueffeloot**
This pr adds the progress text in TP‘s box. TP Decomp now has a website similiar to BOTW Decomp so TP will have the same box layout like BOTW on the website.

### CODE REVIEW

**Comment by TakaRikka** [comment]
if it matters as a tp head, i support this change

**Comment by ethteck** [comment]
@Trueffeloot wouldn't this remove the faq and local section of the site? That's fine if you guys want to not put your content on this site, but then we should probably remove the content we have here so we're not keeping around unused stuff (the games/tp).

**Comment by Trueffeloot** [comment]
Yeah forgot about the old faq. I'll delete that

**Comment by Trueffeloot** [comment]
@ethteck I deleted the faq. Idk if there are still some local tp files, If yes, I will delete them too. Else, this pr is good to go

**Pull request merged**
